# Generated by Django 5.0.7 on 2024-08-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='game',
            name='match1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='match2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='match3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='game',
        ),
        migrations.RemoveField(
            model_name='result',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CasualGameListView',
        ),
        migrations.DeleteModel(
            name='CasualGameView',
        ),
        migrations.DeleteModel(
            name='GameRecordView',
        ),
        migrations.DeleteModel(
            name='RankGameView',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
